language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kubuntu-backports
        packages:
            - cmake
            - g++-5
            - gcc-5

compiler:
  - gcc

install:
    - if [ "$CXX" = "g++"     ]; then export CXX="g++-5" CC="gcc-5"; fi

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

notifications:
  recipients:
    - ben.crowhurst@corvusoft.co.uk
  email:
    on_success: change
    on_failure: always
